# file: chruby/tasks/chruby.yml

- get_url: url=https://github.com/postmodern/chruby/archive/v{{chruby_chruby_version}}.tar.gz
           dest=/opt/build/chruby-{{chruby_chruby_version}}.tar.gz
           sha256sum={{chruby_chruby_checksum}}

- unarchive: src=/opt/build/chruby-{{chruby_chruby_version}}.tar.gz
             dest=/opt/build/
             copy=no
  register: chruby_unarchive

- shell: make install chdir=/opt/build/chruby-{{chruby_chruby_version}}
  when: chruby_unarchive.changed

- template: src=chruby.sh.j2 dest=/etc/profile.d/chruby.sh mode=u+x

