# file: chruby/tasks/ruby.yml

- name: Find out if ruby_version is already installed
  stat: path=/opt/rubies/{{ruby_version}}
  register: ruby_version_folder

- name: Install ruby_version if necessary
  command: '{{ruby_install_command}} ruby {{ruby_version|replace("ruby-", "")}}'
  when: ruby_version_folder.stat.exists == false
