- name: Find out if ruby_version is already installed
  stat: path=/opt/rubies/{{chruby_ruby_version}}
  register: ruby_version_folder

- name: Install ruby_version if necessary
  command: '{{chruby_ruby_install_command}} ruby {{chruby_ruby_version|replace("ruby-", "")}}'
  when: not ruby_version_folder.stat.exists

- name: Install bundler
  gem: >
    executable="{{chruby_chruby_exec_command}} {{chruby_ruby_version}} -- gem"
    name=bundler
    state=present
    user_install=no

# Update the shell integration after installing the new version
- template: src=chruby.sh.j2 dest=/etc/profile.d/chruby.sh mode=u+x
