---
- file: path=/opt/build state=directory

- include: 10-chruby.yml
  tags:    ansible-chruby
- include: 20-ruby-install.yml
  tags:    ansible-chruby
- include: 30-ruby.yml
  tags:    ansible-chruby
- include: 40-remove_outdated_rubies.yml
  tags:    ansible-chruby
