---
- file: path=/opt/build state=directory

- import_tasks: 10-chruby.yml
  tags:    ansible-chruby
- import_tasks: 20-ruby-install.yml
  tags:    ansible-chruby
- import_tasks: 30-ruby.yml
  tags:    ansible-chruby
- import_tasks: 40-remove_outdated_rubies.yml
  tags:    ansible-chruby
